// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnmcoixtxlahzhxrjvzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubWNvaXh0eGxhaHpoeHJqdnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTcwODQsImV4cCI6MjA2MTMzMzA4NH0._ta-q7g53kU7QLJFGtnMTh9N_yItVneyecdzmPC4U74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);